ENV_K8S_API          = 'K8S_API_ENDPOINT'
ENV_K8S_TOKEN        = 'K8S_TOKEN'
ENV_K8S_NAMESPACE    = 'K8S_NAMESPACE'
ENV_K8S_CA           = 'K8S_CA'
ENV_K8S_RESOURCE     = 'K8S_RESOURCE'
ENV_K8S_API_PATH     = 'K8S_API_PATH'
ENV_K8S_API_VERSION  = 'K8S_API_VERSION'
ENV_K8S_API_GROUP    = 'K8S_API_GROUP'
ENV_K8S_NAMESPACED   = 'K8S_NAMESPACED'
ENV_LOG_LEVEL        = 'LOG_LEVEL'
ENV_PLUGIN           = 'WATCHER_PLUGIN'

DEFAULT_K8S_NAMESPACE   = '/var/run/secrets/kubernetes.io/serviceaccount/namespace'
DEFAULT_K8S_TOKEN       = '/var/run/secrets/kubernetes.io/serviceaccount/token'
DEFAULT_K8S_CA       = '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
DEFAULT_K8S_API      = 'kubernetes.default.svc.cluster.local'
DEFAULT_K8S_API_VERSION  = 'v1'
DEFAULT_K8S_API_GROUP    = 'oapi'
DEFAULT_K8S_NAMESPACED  = 'True'
DEFAULT_WATCHER_PLUGIN       = 'simple'
DEFAULT_LOG_LEVEL   = 'INFO'

DESCRIPTION          = 'OpenShift/kubernetes API Watcher Utility. Used to integrate with Third part systems'
